[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openretina"
version = "0.0.1"
description = "Open source retina model architectures and training setups"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.packages]
find = {exclude = ["scripts"]}

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.ruff]
line-length = 120

[tool.ruff.lint]
ignore = ["F722"]
extend-select = ["E501"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 100