[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openretina"
version = "0.0.1"
description = "Open source retina model architectures and training setups"
requires-python = ">=3.8"
dynamic = ["dependencies"]

[tool.setuptools]
packages = ["openretina"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

